name: travelgram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get: 4.6.6
  http: ^1.2.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  latlong2: ^0.9.1
  motion_tab_bar: ^2.0.4
  photo_view: ^0.15.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.1
  timeago: ^3.6.1

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
