name: travelgram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get: 4.6.6
  http: ^1.2.0
  image_picker: ^1.0.8
  intl: ^0.19.0
  motion_tab_bar: ^2.0.4
  pusher_channels_flutter: ^2.2.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.1
  timeago: ^3.6.1
  timeline_tile: ^2.0.0
  

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
